title: Wind and Wine
author: doublo7
email: kriskey@me.com
description: > # this means to ignore newlines until "baseurl:"
  Some places to talk about Robotic Process Automation, and AI in finance industry.
theme: minima
# social links
twitter_username: kriskeycn # DO NOT include the @ character, or else the build will fail!
github_username:  doublo7 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
